#!/bin/sh
# XO-1.5 XO-1.75 XO-4 make a backup of internal storage to a USB drive
set -e
mount /mnt/sda1
mkdir -p /mnt/xo
mount /dev/mmcblk0p2 /mnt/xo

# is this the motherboard partition
if [ -d /mnt/xo/usr/bin ]; then
  motherboard=mmcblk0
  sdcard=mmcblk1
else
  motherboard=mmcblk1
  sdcard=mmcblk0
fi
umount /mnt/xo/mmcblk0p2

mount ${motherboard}p2 /mnt/xo
mkdir -p /mnt/xo/boot
mount ${motherboard}p1 /mnt/xo/boot
mkdir -p /mnt/xo/library
mount ${sdcard}p2 /mnt/xo/library
mkdir -p /mnt/xo/opt
mount ${sdcard}p1 /mnt/xo/opt
sleep 10
tar --create --directory /mnt/xo --file /mnt/sda1/xo.tar .
umount /mnt/xo/boot
#rmdir /mnt/xo/boot
umount /mnt/xo/library
rmdir /mnt/xo/library
umount /mnt/xo/opt
rmdir /mnt/xo/opt
umount /mnt/xo
rmdir /mnt/xo
umount /mnt/sda1
echo ok
